#!/bin/bash

set -eu
set -o pipefail

if [ -f /etc/redhat-release ]; then
  CLOUD_INIT_VERSION=`rpm -q --queryformat '%{version}' cloud-init`
  if [[ $CLOUD_INIT_VERSION =~ "0.6." ]]; then
    rpm -e cloud-init
    rpm -i python-cloud-init
  fi
elif [ -f /etc/debian_version ]; then
  CLOUD_INIT_VERSION=`dpkg -s cloud-init | grep Version | cut -d: -f2`
  if [[ $CLOUD_INIT_VERSION =~ "0.6." ]]; then
    dpkg -r cloud-init
    add-apt-repository ppa:al592b/ppa
    apt-get -y install python-cloud-init
  fi
else
  echo "Only redhat and debian family OS supported at this time"
  exit 1
fi
